ci:
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.31.0
    hooks:
      - id: yapf
        name: Format code

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--multi_line_output, '4', --skip, .gitignore, --skip, __init__.py]
        name: Sort imports
