package:
  name: pytorch-geometric
  version: 2.5.0

source:
  url: https://files.pythonhosted.org/packages/01/8f/82abc47a9b37d3a1611a3d0532f096de550a037fb92f659e4eae4ac9cd31/torch_geometric-2.5.0.tar.gz

requirements:
  host:
    - pip
    - flit-core
    - python {{ environ.get('PYTHON_VERSION') }}

  run:
    - python {{ environ.get('PYTHON_VERSION') }}
    - {{ environ.get('CONDA_PYTORCH_CONSTRAINT') }}
    - {{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT') }}
    - psutil
    - fsspec
    - tqdm
    - jinja2
    - pyparsing
    - numpy
    - scipy
    - aiohttp
    - requests
    - scikit-learn

build:
  string: py{{ environ.get('PYTHON_VERSION').replace('.', '') }}_torch_{{ environ['TORCH_VERSION'] }}_{{ environ['CUDA_VERSION'] }}
  script: pip install .

test:
  imports:
    - torch_geometric
    - torch_geometric.nn
    - torch_geometric.data
    - torch_geometric.utils
    - torch_geometric.datasets
    - torch_geometric.transforms

about:
  home: https://github.com/pyg-team/pytorch_geometric
  license: MIT
  summary: Graph Neural Network Library for PyTorch
