# IP addresses for all nodes.
# Note: The first 3 params are expected to form usernames@nodes:ports
# to access each node by ssh
nodes:
  - 0.0.0.0
  - 1.1.1.1
# ssh ports for each node.
ports: [22, 22]
# username for remote IPs.
usernames:
  - your_username_for_node_0
  - your_username_for_node_1

# path to python with GLT envs for each node
python_bins:
  - /path/to/python
  - /path/to/python

# dataset name, e.g. ogbn-products, ogbn-papers100M.
# Note: make sure the name of dataset_root_dir the same as the dataset name.
dataset: ogbn-products

# in_channel and out_channel for the dataset
# The following two params are specific to datasets
# E.g.:
#   For ogbn-products: in_channel=100, out_channel=47
#   For ogbn-papers100M: in_channel=128, out_channel=172
in_channel: 100
out_channel: 47

# path to the pytorch_geometric directory
dst_paths:
  - /path/to/pytorch_geometric
  - /path/to/pytorch_geometric

# setup visible cuda devices for each node.
visible_devices:
  - 0,1,2,3
  - 0,1,2,3
