out_dir: results
dataset:
  format: OGB
  name: ogbg-molhiv
  task: graph
  task_type: classification
  node_encoder: true
  node_encoder_name: Atom
  edge_encoder: true
  edge_encoder_name: Bond
train:
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
  sampler: full_batch
model:
  type: gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add
gnn:
  layers_pre_mp: 1
  layers_mp: 3              # number of DelayGNN layers, i.e. timesteps
  layers_post_mp: 1         # the 'head', i.e. final MLP
  dim_inner: 300
  layer_type: my_gcnconv
  stage_type: delay_gnn
  batchnorm: true
  act: prelu
  dropout: 0.0
  agg: mean
  normalize_adj: false
optim:
  optimizer: adam
  base_lr: 0.01
  max_epoch: 1
tensorboard_each_run: True
delay:
  max_k: 3

  # do we need to do a special thing for the general gnn model as well? i.e. encoder + stage + head ?
