name: Documentation

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:

jobs:

  make_html:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
        torch-version: [1.13.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup packages
        uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}
          torch-version: ${{ matrix.torch-version }}

      - name: Install main package
        run: |
          pip install git+https://github.com/pyg-team/pyg_sphinx_theme.git
          pip install -e .

      - name: Build documentation
        run: |
          cd docs && make clean && make html SPHINXOPTS="-W"  # Fail on warning.
