name: Examples

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"  # Everyday at 7:00am UTC/11:00pm PST

jobs:

  pytest:
    if: github.repository == 'pyg-team/pytorch_geometric'
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
        torch-version: [1.13.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup packages
        uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}
          torch-version: ${{ matrix.torch-version }}

      - name: Install main package
        run: |
          pip install .[benchmark]

      - name: Run GCN on Cora
        run: |
          python examples/gcn.py --wandb
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

      - name: Run GAT on Cora
        run: |
          python examples/gat.py --wandb
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

      - name: Run GIN on MUTAG
        run: |
          python examples/mutag_gin.py --wandb
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

      - name: Run GNNExplainer
        run: |
          python examples/gnn_explainer.py
