name: Full GPU Testing

# on:  # yamllint disable-line rule:truthy
#   workflow_dispatch:
#   schedule:
#     - cron: "0 6 * * *"  # Everyday at 6:00am UTC/10:00pm PST
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:

jobs:

  pytest:
    if: github.repository == 'pyg-team/pytorch_geometric'
    runs-on: [self-hosted, cuda]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup packages
        uses: ./.github/actions/setup
        with:
          cuda-version: 'cu118'

      - name: Install main package
        run: |
          pip install -e .[full,test]

      - name: Run tests
        run: |
          FULL_TEST=1 pytest --cov --cov-report=xml
        shell: bash
