name: Minimal Installation

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:

jobs:

  import:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
        torch-version: [1.13.0]

    steps:
      - uses: actions/checkout@v3
      - uses: .github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}
          torch-version: ${{ matrix.torch-version }}

      - name: Install main package
        run: |
          pip install -e .[test]

      - name: Test imports
        run: |
          python -c "import torch_geometric"
          python -c "import torch_geometric.datasets"
          python -c "import torch_geometric.nn"
          python -c "import torch_geometric.graphgym"

      - name: Run tests
        run: |
          pytest
