name: Nightly Build

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"  # Everyday at 6:00am UTC/10:00pm PST
  push:
    branches:
      - master
  pull_request:

jobs:

  sdist:
    if: github.repository == 'pyg-team/pytorch_geometric'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Customize build version
        run: |
          sed -i "s/name='torch_geometric'/name='pyg-nightly'/" setup.py
          sed -i "s/2.0.5/2.0.5.$TODAY/" setup.py
          sed -i "s/2.0.5/2.0.5.$TODAY/" torch_geometric/__init__.py
        env:
          TODAY: date +'%Y%m%d'

      - name: Build package
        run: python setup.py sdist
